### PR TITLE
Fix link to examples

### PR DESCRIPTION
**Pull request by declension**
Was sending readers to the fork not this repo's example

### CODE REVIEW

**Comment by declension** [comment]
Shall I close this or can it be merged?

**Comment by BrianHicks** [comment]
hey @declension! I think nobody got a ping that this was ready to look at. Sorry! Looks fine to me, though.

@NoRedInkBot r+

**Comment by BrianHicks** [comment]
whoops, wrong robot command

duet r+

**Comment by BrianHicks** [comment]
well, whatever. Gotta have a config after all (I thought we didn't!) Sorry for the noise; I'm trying to figure out a new setup and this PR showed up as needing review. Gonna just merge manually now.

**Pull request merged**
